# Multi-stage image for nas-port-mcp
# Generated by genproj (docker-container capability). Adjust for your application.
#
# Stage 1 (build): copies the full source tree, installs dev dependencies and
# builds the application. Stage 2 (runtime): copies only the build output and
# production dependencies, keeping the final image small.

FROM python:3.12-slim AS build
WORKDIR /app
COPY requirements.txt* ./
RUN python -m venv /opt/venv
RUN /opt/venv/bin/pip install --no-cache-dir -r requirements.txt
COPY . .

FROM python:3.12-slim
WORKDIR /app
ENV PATH="/opt/venv/bin:$PATH"
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 3001

# HEALTHCHECK skipped for python images by default (install curl/wget first)
# TODO: set your entrypoint, e.g.: CMD ["python", "main.py"]
CMD ["python", "main.py"]
